common: &common
  encoding: utf8
  adapter: postgresql
  host: localhost
  username: rex
  password:

development:
  <<: *common
  database: rex_development

production:
  <<: *common
  database: rex_production

test:
  <<: *common
  database: rex_test
